ip = '0.0.0.0'
port = 6543
client_data_path = 'client_data.db'
client_data_name = 'client_data'
tmp_var_name = "WAIT"
res_html_start = "<body><h1>"
res_html_end = "</h1></body>"
ans_not_ready = "The answer isn\'t ready yet"
ans_not_id = 'The ID {} isn\'t exists'
ans_good = "res of id {} is {}"
err_exist_id = 'You entered an exist id!'
succ_sent = 'The args sent!'
not_succ_sent = 'Part of the args didn\'t sent!'
